#!/usr/bin/env bash

set -eo pipefail

PYTHON_VERSION=3.10
NODEJS_VERSION=16

function install_homebrew {
    sudo apt-get install build-essential procps curl file git
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

    brew install \
        bash \
        bat \
        difftastic \
        fd \
        fish \
        fzf \
        gcc \
        gh \
        git \
        git-delta \
        glow \
        libffi \
        ripgrep \
        starship \
        tmux \
        todo-txt \
        vivid \
        watchexec \
        zoxide
    brew install neovim --HEAD

    export CC="$HOMEBREW_PREFIX/bin/gcc-11"
}

function install_asdf {
    brew install asdf
    source "$HOMEBREW_PREFIX/opt/asdf/asdf.sh"

    asdf plugin add direnv
    asdf direnv setup --shell fish --version latest
    asdf global direnv latest

    asdf plugin add golang
    asdf install golang latest
    asdf global golang latest

    asdf plugin add nodejs
    asdf install nodejs latest:$NODEJS_VERSION
    asdf global nodejs latest:$NODEJS_VERSION

    asdf plugin add python
    asdf install python latest:$PYTHON_VERSION
    asdf global python latest:$PYTHON_VERSION

    asdf plugin add rust
    asdf install rust stable
    asdf global rust stable

    asdf reshim
}

function install_plugin_managers {
    # Fish - fisher
    fish -c "curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher"

    # Neovim - packer
    git clone --depth 1 https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim

    # Tmux - tpm
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
}

function setup_misc {
    FISH_PATH=$(which fish)
    echo "$FISH_PATH" | sudo tee --append /etc/shells
    chsh -s "$FISH_PATH"

    gh auth login

    (cd "$HOME/.dotfiles" && git config remote.origin.url git@github.com:petertriho/dotfiles.git)
}

function main {
    install_homebrew
    install_asdf
    install_plugin_managers

    setup_misc
}

main
