right_format = "${custom.arch}${time}"

[custom.arch]
command = "uname -m"
when = "true"

[battery]
disabled = true

[directory]
truncate_to_repo = false
fish_style_pwd_dir_length = 1

[time]
disabled = false
