select = [
  "F",     # pyflakes
  "E",     # pycodestyle
  "W",     # pycodestyle
  # "I",     # isort
  "N",     # pep8-naming
  "D",     # pydocstyle
  "ASYNC", # flake8-async
  "B",     # flake8-bugbear
  "PL",    # pylint
  "TRY",   # tryceratops
  "FLY",   # flynt
  "RUF",   # ruff
]
