local sidebars = {
    "dbui",
    "DiffViewFiles",
    "Mundo",
    "MundoDiff",
    "NvimTree",
    "Outline",
    "UltestSummary",
}

return {
    common = {
        "css",
        "dockerfile",
        "fish",
        "go",
        "graphql",
        "html",
        "javascript",
        "json",
        "jsonc",
        "lua",
        "markdown",
        "python",
        "rust",
        "scss",
        "svelte",
        "toml",
        "typescript",
        "vim",
        "yaml",
    },
    extras = {
        "javascriptreact",
        "jsx",
        "sh",
        "typescriptreact",
    },
    excludes = {
        "",
        "fugitive",
        "fugitiveblame",
        "help",
        "lspinfo",
        "NeogitStatus",
        "packer",
        "prompt",
        "qf",
        "TelescopePrompt",
        unpack(sidebars),
    },
    sidebars = sidebars,
}
