return {
    "pwntester/octo.nvim",
    requires = {
        "nvim-tree/nvim-web-devicons",
        "nvim-telescope/telescope.nvim",
    },
    cmd = "Octo",
    setup = function()
        require("which-key").register({
            A = { "<CMD>Octo actions<CR>", "actions" },
            I = { "<CMD>Octo issue list<CR>", "issues" },
            G = { "<CMD>Octo gist list<CR>", "gist" },
            R = { "<CMD>Octo repo list<CR>", "repos" },
            P = { "<CMD>Octo pr list<CR>", "prs" },
        }, {
            prefix = ",",
            mode = "n",
            silent = true,
            noremap = true,
        })
    end,
    config = function()
        require("octo").setup({
            mappings = {
                issue = {
                    close_issue = { lhs = ",ic", desc = "close issue" },
                    reopen_issue = { lhs = ",io", desc = "reopen issue" },
                    list_issues = { lhs = ",il", desc = "list open issues on same repo" },
                    reload = { lhs = "<C-r>", desc = "reload issue" },
                    open_in_browser = { lhs = "<C-b>", desc = "open issue in browser" },
                    copy_url = { lhs = "<C-y>", desc = "copy url to system clipboard" },
                    add_assignee = { lhs = ",aa", desc = "add assignee" },
                    remove_assignee = { lhs = ",ad", desc = "remove assignee" },
                    create_label = { lhs = ",lc", desc = "create label" },
                    add_label = { lhs = ",la", desc = "add label" },
                    remove_label = { lhs = ",ld", desc = "remove label" },
                    goto_issue = { lhs = ",gi", desc = "navigate to a local repo issue" },
                    add_comment = { lhs = ",ca", desc = "add comment" },
                    delete_comment = { lhs = ",cd", desc = "delete comment" },
                    next_comment = { lhs = "]c", desc = "go to next comment" },
                    prev_comment = { lhs = "[c", desc = "go to previous comment" },
                    react_hooray = { lhs = ",ep", desc = "add/remove 🎉 reaction" },
                    react_heart = { lhs = ",eh", desc = "add/remove ❤️ reaction" },
                    react_eyes = { lhs = ",ee", desc = "add/remove 👀 reaction" },
                    react_thumbs_up = { lhs = ",e+", desc = "add/remove 👍 reaction" },
                    react_thumbs_down = { lhs = ",e-", desc = "add/remove 👎 reaction" },
                    react_rocket = { lhs = ",er", desc = "add/remove 🚀 reaction" },
                    react_laugh = { lhs = ",el", desc = "add/remove 😄 reaction" },
                    react_confused = { lhs = ",ec", desc = "add/remove 😕 reaction" },
                },
                pull_request = {
                    checkout_pr = { lhs = ",po", desc = "checkout PR" },
                    merge_pr = { lhs = ",pm", desc = "merge commit PR" },
                    squash_and_merge_pr = { lhs = ",psm", desc = "squash and merge PR" },
                    list_commits = { lhs = ",pc", desc = "list PR commits" },
                    list_changed_files = { lhs = ",pf", desc = "list PR changed files" },
                    show_pr_diff = { lhs = ",pd", desc = "show PR diff" },
                    add_reviewer = { lhs = ",va", desc = "add reviewer" },
                    remove_reviewer = { lhs = ",vd", desc = "remove reviewer request" },
                    close_issue = { lhs = ",ic", desc = "close PR" },
                    reopen_issue = { lhs = ",io", desc = "reopen PR" },
                    list_issues = { lhs = ",il", desc = "list open issues on same repo" },
                    reload = { lhs = "<C-r>", desc = "reload PR" },
                    open_in_browser = { lhs = "<C-b>", desc = "open PR in browser" },
                    copy_url = { lhs = "<C-y>", desc = "copy url to system clipboard" },
                    goto_file = { lhs = "gf", desc = "go to file" },
                    add_assignee = { lhs = ",aa", desc = "add assignee" },
                    remove_assignee = { lhs = ",ad", desc = "remove assignee" },
                    create_label = { lhs = ",lc", desc = "create label" },
                    add_label = { lhs = ",la", desc = "add label" },
                    remove_label = { lhs = ",ld", desc = "remove label" },
                    goto_issue = { lhs = ",gi", desc = "navigate to a local repo issue" },
                    add_comment = { lhs = ",ca", desc = "add comment" },
                    delete_comment = { lhs = ",cd", desc = "delete comment" },
                    next_comment = { lhs = "]c", desc = "go to next comment" },
                    prev_comment = { lhs = "[c", desc = "go to previous comment" },
                    react_hooray = { lhs = ",ep", desc = "add/remove 🎉 reaction" },
                    react_heart = { lhs = ",eh", desc = "add/remove ❤️ reaction" },
                    react_eyes = { lhs = ",ee", desc = "add/remove 👀 reaction" },
                    react_thumbs_up = { lhs = ",e+", desc = "add/remove 👍 reaction" },
                    react_thumbs_down = { lhs = ",e-", desc = "add/remove 👎 reaction" },
                    react_rocket = { lhs = ",er", desc = "add/remove 🚀 reaction" },
                    react_laugh = { lhs = ",el", desc = "add/remove 😄 reaction" },
                    react_confused = { lhs = ",ec", desc = "add/remove 😕 reaction" },
                },
                review_thread = {
                    goto_issue = { lhs = ",gi", desc = "navigate to a local repo issue" },
                    add_comment = { lhs = ",ca", desc = "add comment" },
                    add_suggestion = { lhs = ",sa", desc = "add suggestion" },
                    delete_comment = { lhs = ",cd", desc = "delete comment" },
                    next_comment = { lhs = "]c", desc = "go to next comment" },
                    prev_comment = { lhs = "[c", desc = "go to previous comment" },
                    select_next_entry = { lhs = "]q", desc = "move to previous changed file" },
                    select_prev_entry = { lhs = "[q", desc = "move to next changed file" },
                    close_review_tab = { lhs = "<C-c>", desc = "close review tab" },
                    react_hooray = { lhs = ",ep", desc = "add/remove 🎉 reaction" },
                    react_heart = { lhs = ",eh", desc = "add/remove ❤️ reaction" },
                    react_eyes = { lhs = ",ee", desc = "add/remove 👀 reaction" },
                    react_thumbs_up = { lhs = ",e+", desc = "add/remove 👍 reaction" },
                    react_thumbs_down = { lhs = ",e-", desc = "add/remove 👎 reaction" },
                    react_rocket = { lhs = ",er", desc = "add/remove 🚀 reaction" },
                    react_laugh = { lhs = ",el", desc = "add/remove 😄 reaction" },
                    react_confused = { lhs = ",ec", desc = "add/remove 😕 reaction" },
                },
                submit_win = {
                    approve_review = { lhs = "<C-a>", desc = "approve review" },
                    comment_review = { lhs = "<C-m>", desc = "comment review" },
                    request_changes = { lhs = "<C-r>", desc = "request changes review" },
                    close_review_tab = { lhs = "<C-c>", desc = "close review tab" },
                },
                review_diff = {
                    add_review_comment = { lhs = ",ca", desc = "add a new review comment" },
                    add_review_suggestion = { lhs = ",sa", desc = "add a new review suggestion" },
                    focus_files = { lhs = ",e", desc = "move focus to changed file panel" },
                    toggle_files = { lhs = ",b", desc = "hide/show changed files panel" },
                    next_thread = { lhs = "]t", desc = "move to next thread" },
                    prev_thread = { lhs = "[t", desc = "move to previous thread" },
                    select_next_entry = { lhs = "]q", desc = "move to previous changed file" },
                    select_prev_entry = { lhs = "[q", desc = "move to next changed file" },
                    close_review_tab = { lhs = "<C-c>", desc = "close review tab" },
                    toggle_viewed = { lhs = ",,", desc = "toggle viewer viewed state" },
                },
                file_panel = {
                    next_entry = { lhs = "j", desc = "move to next changed file" },
                    prev_entry = { lhs = "k", desc = "move to previous changed file" },
                    select_entry = { lhs = "<cr>", desc = "show selected changed file diffs" },
                    refresh_files = { lhs = "R", desc = "refresh changed files panel" },
                    focus_files = { lhs = ",e", desc = "move focus to changed file panel" },
                    toggle_files = { lhs = ",b", desc = "hide/show changed files panel" },
                    select_next_entry = { lhs = "]q", desc = "move to previous changed file" },
                    select_prev_entry = { lhs = "[q", desc = "move to next changed file" },
                    close_review_tab = { lhs = "<C-c>", desc = "close review tab" },
                    toggle_viewed = { lhs = ",,", desc = "toggle viewer viewed state" },
                },
            },
        })

        require("which-key").register({
            [","] = "toggle-viewed",
            f = "focus-files",
            t = "toggle-files",
            a = {
                name = "+assignee",
                a = "add",
                d = "delete",
            },
            c = {
                name = "+comment",
                a = "add",
                d = "delete",
            },
            e = {
                name = "+emoji",
                ["+"] = "thumbs-up 👍",
                ["-"] = "thumbs-down 👎",
                c = "confused 😕",
                e = "eyes 👀 ",
                h = "heart ❤️",
                l = "laugh 😄",
                p = "party 🎉",
                r = "rocket 🚀",
            },
            i = {
                name = "+issue",
                c = "close",
                l = "list",
                o = "open",
            },
            g = {
                name = "+go",
                i = "issue",
            },
            l = {
                name = "+label",
                a = "add",
                c = "create",
                d = "delete",
            },
            p = {
                name = "+pr",
                c = "commits-list",
                d = "diff",
                f = "files-changed",
                m = "merge",
                o = "checkout",
                r = { "<CMD>Octo pr ready<CR>", "ready" },
                s = { "<CMD>Octo pr checks<CR>", "status" },
            },
            r = {
                name = "+review",
                ["<CR>"] = { "<CMD>Octo review submit<CR>", "submit" },
                c = { "<CMD>Octo review comments<CR>", "comments" },
                d = { "<CMD>Octo review discard<CR>", "discard" },
                r = { "<CMD>Octo review resume<CR>", "resume" },
                s = { "<CMD>Octo review start<CR>", "start" },
            },
            s = {
                name = "+suggestion",
                a = "add",
            },
            v = {
                name = "+reviewer",
                a = "add",
                d = "delete",
            },
        }, {
            prefix = ",",
            mode = "n",
            silent = true,
            noremap = true,
        })
    end,
}
